name: mhamrah
description: اپلیکیشنی برای مشاوره تحصیلی به صورت غیر حصوری و آنلاین مخصوص دانش اموزان

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons:
  charts_flutter:
  splashscreen:
  firebase_messaging:
  table_sticky_headers:
  web_socket_channel:
  shelf_web_socket:
  http:
#  localstorage:
  scroll_to_index:
  file_picker:
  image_picker:
  photo_view:
  open_file:
  url_audio_stream:
  audioplayers:
  chewie_audio:
  chewie:
  video_player:
  uni_links:
  flutter_bloc:
#  zarinpal: 1.0.3
  sentry: ^3.0.1
  firebase_crashlytics:
  #  video_player_web:
#  image_picker_web:
#  flutter_file_dialog:
  dwds:
  flushbar:
  percent_indicator:
  auto_direction:
  url_launcher:
  device_apps:
  android_intent:
  auto_size_text:
  custom_switch:
  bubbled_navigation_bar:
  fluttertoast:
  flutter_slidable:
  transformer_page_view:
  flutter_circular_chart:
  shamsi_date:
  flutter_audio_recorder:
  cached_network_image:
  flutter_cache_manager:
  path_provider:
  notification_permissions:
#  app_usage:
  vibration:
  package_info:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon/4.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/img/2.png
    - assets/img/2-2.png
    - assets/img/3.png
    - assets/img/3-2.png
    - assets/img/4.png
    - assets/appIcon/4.png
    - assets/img/4-2.png
    - assets/img/5.png
    - assets/img/5-2.png
    - assets/img/11.png
    - assets/img/12.png
    - assets/img/13.png
    - assets/img/14.png
    - assets/img/15.png
    - assets/img/17.png
    - assets/img/25.png
    - assets/img/27.png
    - assets/img/30.png
    - assets/img/31.png
    - assets/img/telegram.png
    - assets/img/instagram.png
    - assets/img/whatsapp.png
  fonts:
    - family: traffic
      fonts:
        - asset: assets/font/BTrafcBd.ttf
    - family: ntraffic
      fonts:
        - asset: assets/font/TRAFFIC5.TTF
    - family: iransans
      fonts:
        - asset: assets/font/IRAN-Sans-Bold.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
